version: "3"

services:
  ros_master:
    image: ros:noetic
    container_name: ros_master
    networks:
      - simulator_network
    restart: always
    command: stdbuf -o L roscore

  simulator_container:
    image: shapenet-simulator:v0
    container_name: simulator_container
    depends_on:
      - ros_master
    tty: true
    networks:
      - simulator_network
    volumes:
      - ./.env:/.env:r
      - ./src/simulator/models:/src/simulator/models:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    environment:
      - ROS_MASTER_URI=http://ros_master:11311
      - PYTHONUNBUFFERED=1
      - DISPLAY=unix${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia

networks:
  simulator_network:
    driver: bridge
