version: "3"

services:
  ros_master:
    image: ros:noetic
    container_name: ros_master
    network_mode: host
    restart: always
    command: stdbuf -o L roscore

  simulator_container:
    image: shapenet-simulator:v0
    container_name: simulator_container
    depends_on:
      - ros_master
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - ./src/simulator/models/:/shapenet_simulator/src/simulator/models/:rw
      - ./src/simulator/new_scene.sdf:/shapenet_simulator/src/simulator/new_scene.sdf:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - PYTHONUNBUFFERED=1
      - DISPLAY=unix${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
