###### configuration for random_planner ######
action_space:
  min_height: 0.1
  radius: 2

simulation_bridge:
  camera_type: rgbd_camera
  rgb_noise: 0 # std of rgb measurment
  depth_noise: 0 # std of rgb measurment

scene_range: [0.3, 3.3]
view_change: 1.5
num_candidates: 50
initial_type: random
use_opencv: true # std of rgb measurment
